# Generated by Django 2.2.7 on 2019-11-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Grup İsim')),
                ('resim', models.FileField(blank=True, upload_to='grup_resim/', verbose_name='Grup Resim')),
                ('grup_bugday', models.IntegerField(default=0, verbose_name='Grup Toplam Buğday')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='Kategori ismi')),
                ('resim', models.FileField(blank=True, upload_to='kategori_resim/', verbose_name='Kategori Resim')),
            ],
        ),
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50, verbose_name='Nick Name')),
                ('e_mail', models.EmailField(max_length=100, verbose_name='Üye E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Üye Giriş Parolası')),
                ('bugday', models.IntegerField(default=0, verbose_name='Bugday Adet')),
                ('uyelik_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Üye Olma Tarihi')),
                ('forget', models.CharField(blank=True, max_length=20, verbose_name='Forget Link')),
                ('engelle', models.BooleanField(default=0, verbose_name='Engelle')),
            ],
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=500, verbose_name='Soru')),
                ('sik_1', models.CharField(max_length=500, verbose_name='Şık 1 (Doğru Cevap)')),
                ('sik_2', models.CharField(max_length=500, verbose_name='Şık 2')),
                ('sik_3', models.CharField(max_length=500, verbose_name='Şık 3')),
                ('sik_4', models.CharField(max_length=500, verbose_name='Şık 4')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Kategori')),
            ],
        ),
    ]
