# Generated by Django 2.2.7 on 2019-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayarlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunluk', models.IntegerField(default=0, verbose_name='Günlük Toplam')),
                ('aylik', models.IntegerField(default=0, verbose_name='Aylık Toplam')),
                ('toplam', models.IntegerField(default=0, verbose_name='Ömürlük Toplam')),
            ],
        ),
    ]
