# Generated by Django 2.2.7 on 2019-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191126_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeler',
            name='cozulen_soru',
            field=models.IntegerField(default=0, verbose_name='Bugday Adet'),
        ),
    ]
