# Generated by Django 2.2.7 on 2019-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191126_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='gunluk_cozulen_soru',
            field=models.IntegerField(default=0, verbose_name='Günlük Çözülen Soru'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='gunluk_ziyaretci',
            field=models.IntegerField(default=0, verbose_name='Günlük Ziyaretçi'),
        ),
        migrations.AddField(
            model_name='ayarlar',
            name='toplam_ziyaretci',
            field=models.IntegerField(default=0, verbose_name='Toplam Ziyaretçi'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='cozulen_soru',
            field=models.IntegerField(default=0, verbose_name='Toplam Çözülen Soru'),
        ),
    ]
