# Generated by Django 2.2.7 on 2019-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191126_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='gunluk_toplam',
            field=models.IntegerField(default=0, verbose_name='Günlük Toplam Buğday'),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='toplam',
            field=models.IntegerField(default=0, verbose_name='Ömürlük Toplam Buğday'),
        ),
    ]
