# Generated by Django 2.2.7 on 2019-11-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ayarlar_toplam_soru_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='aciklama',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kategori Açıklama'),
        ),
    ]
