# Generated by Django 2.2.7 on 2019-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_kategori_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='aciklama',
            field=models.CharField(blank=True, default='aaa', max_length=300, verbose_name='Kategori Açıklama'),
        ),
    ]
