# Generated by Django 2.2.7 on 2019-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191126_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadi', models.CharField(max_length=500, verbose_name='Kullanıcı Adı')),
                ('kbasi', models.CharField(max_length=500, verbose_name='Konu Başlığı')),
                ('kicerik', models.CharField(max_length=5000, verbose_name='Konu İçeriği')),
            ],
        ),
    ]
