# Generated by Django 2.2.7 on 2019-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='resim_alt',
            field=models.CharField(default='Buğday Bağışla', max_length=100, verbose_name='Resim Alt Açıklama'),
        ),
    ]
